# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: hone
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  RUN_WORKFLOW: false
jobs:
  hone:
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    # @todo #716:35min Enable hone.yml and jmh.yml (hone-dependent workflow) after hone will be fixed.
    #  At present, the hone is unable to generate the correct optimized byte code for Groovy, see
    #  this issue: https://github.com/objectionary/hone-maven-plugin/issues/297. Also, the plugin run
    #  is time-consuming, we should enable it only after the plugin will have stable execution time,
    #  in order to not disturb the development in this repository.
    if: ${{ vars.RUN_WORKFLOW == 'true' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 23
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ubuntu-surefire-jdk-23-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-surefire-jdk-23-maven-
      - run: |
          mvn clean install -Phone --errors --batch-mode
