# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: jmh
'on':
  pull_request:
    branches:
      - master
env:
  RUN_WORKFLOW: false
jobs:
  jmh:
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    if: ${{ vars.RUN_WORKFLOW == 'true' }}
    steps:
      - name: Run JMH Benchmark Action
        uses: volodya-lombrozo/jmh-benchmark-action@v1
        with:
          java-version: "11"
          base-ref: "master"
          benchmark-command: |
            mvn jmh:benchmark -Djmh.rf=json -Djmh.rff=benchmark.json
          benchmark-file: "benchmark.json"
