# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: motives
'on':
  push:
    tags:
      - '*'
concurrency:
  group: motives-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motives:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes pandoc
      - run: .github/motives.sh "${{ github.ref_name }}"
      - uses: JamesIves/github-pages-deploy-action@v4.7.6
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
